/*
 * Generated by XDoclet - Do not edit!
 */
package org.eMayor.FormatTransformation.interfaces;

/**
 * Home interface for TemplateManager.
 */
public interface TemplateManagerHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TemplateManager";
   public static final String JNDI_NAME="ejb/TemplateManager";

   public org.eMayor.FormatTransformation.interfaces.TemplateManager create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
