/*
 * Generated by XDoclet - Do not edit!
 */
package org.eMayor.FormatTransformation.interfaces;

/**
 * Home interface for Transformer.
 */
public interface TransformerHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Transformer";
   public static final String JNDI_NAME="ejb/Transformer";

   public org.eMayor.FormatTransformation.interfaces.Transformer create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
