<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:impl="http://interfaces.FormatTransformation.eMayor.org" xmlns:intf="http://interfaces.FormatTransformation.eMayor.org" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://interfaces.FormatTransformation.eMayor.org">
	<wsdl:message name="transformRequest">
		<wsdl:part name="documentToTransform" type="xsd:string"/>
		<wsdl:part name="typeOfTransformation" type="xsd:string"/>
		<wsdl:part name="typeOfDocument" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="transformResponse">
		<wsdl:part name="transformReturn" type="xsd:string"/>
	</wsdl:message>
	<wsdl:portType name="Transformer">
		<wsdl:operation name="transform" parameterOrder="documentToTransform typeOfTransformation typeOfDocument">
			<wsdl:input name="transformRequest" message="impl:transformRequest"/>
			<wsdl:output name="transformResponse" message="impl:transformResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="TransformerSoapBinding" type="impl:Transformer">
		<wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="transform">
			<wsdlsoap:operation/>
			<wsdl:input>
				<wsdlsoap:body use="literal" namespace="http://interfaces.FormatTransformation.eMayor.org"/>
			</wsdl:input>
			<wsdl:output>
				<wsdlsoap:body use="literal" namespace="http://interfaces.FormatTransformation.eMayor.org"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="TransformerService">
		<wsdl:port name="Transformer" binding="impl:TransformerSoapBinding">
			<wsdlsoap:address location="http://localhost:8080/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
