/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.notification.wrapper.interfaces;

/**
 * Remote interface for BPELNotificationWrapper.
 */
public interface BPELNotificationWrapper
   extends javax.ejb.EJBObject
{
   /**
    * Business method
    */
   public void sendNotificationMessage( java.lang.String medium,java.lang.String userId,java.lang.String subject,java.lang.String body,java.lang.String message )
      throws org.emayor.notification.exception.NotificationException, java.rmi.RemoteException;

}
