/*
 * Generated by XDoclet - Do not edit!
 */
package org.eMayor.AdaptationLayer.interfaces;

/**
 * Remote interface for E2M.
 */
public interface E2M
   extends javax.ejb.EJBObject
{
   /**
    * Business method
    */
   public java.lang.String ServiceRequestPropagator( java.lang.String ResidenceCertificationRequest,int ServiceSelection )
      throws java.rmi.RemoteException;

}
