/*
 * Generated by XDoclet - Do not edit!
 */
package org.eMayor.AdaptationLayer.interfaces;

/**
 * Home interface for E2M.
 */
public interface E2MHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/E2M";
   public static final String JNDI_NAME="ejb/E2M";

   public org.eMayor.AdaptationLayer.interfaces.E2M create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
