/*
 * Generated by XDoclet - Do not edit!
 */
package org.eMayor.AdaptationLayer.interfaces;

/**
 * Local home interface for E2M.
 */
public interface E2MLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/E2MLocal";
   public static final String JNDI_NAME="E2MLocal";

   public org.eMayor.AdaptationLayer.interfaces.E2MLocal create()
      throws javax.ejb.CreateException;

}
