/*
 * Generated by XDoclet - Do not edit!
 */
package org.eMayor.AdaptationLayer.interfaces;

/**
 * Local interface for E2M.
 */
public interface E2MLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Business method
    */
   public java.lang.String ServiceRequestPropagator( java.lang.String ResidenceCertificationRequest,int ServiceSelection ) ;

}
