/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for AccessSession.
 */
public interface AccessSessionLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Business Method
    */
   public boolean authenticateUser( javax.security.cert.X509Certificate certificate ) throws org.emayor.servicehandling.kernel.AccessSessionException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.interfaces.ServiceSessionLocal[] getAllServiceSessions(  ) throws org.emayor.servicehandling.kernel.AccessSessionException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.interfaces.ServiceSessionLocal getServiceSession( java.lang.String ssid ) throws org.emayor.servicehandling.kernel.AccessSessionException;

   /**
    * Business Method
    */
   public java.lang.String startServiceSession( java.lang.String serviceName ) throws org.emayor.servicehandling.kernel.AccessSessionException;

   /**
    * Business Method
    */
   public boolean stopServiceSession( java.lang.String ssid ) throws org.emayor.servicehandling.kernel.AccessSessionException;

   /**
    * Business Method
    */
   public boolean stopAllServiceSessions(  ) throws org.emayor.servicehandling.kernel.AccessSessionException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.ServiceInfo[] listAvailableServices(  ) throws org.emayor.servicehandling.kernel.AccessSessionException;

   /**
    * Business Method
    */
   public boolean stop(  ) throws org.emayor.servicehandling.kernel.AccessSessionException;

   /**
    * Business Method
    */
   public org.emayor.policyenforcer.C_UserProfile getUserProfile(  ) throws org.emayor.servicehandling.kernel.AccessSessionException;

   /**
    * Business Method
    */
   public java.lang.String getSessionId(  ) throws org.emayor.servicehandling.kernel.SessionException;

}
