/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local home interface for AccessSessionEntity.
 */
public interface AccessSessionEntityLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AccessSessionEntityLocal";
   public static final String JNDI_NAME="AccessSessionEntityLocal";

   public org.emayor.servicehandling.interfaces.AccessSessionEntityLocal create(java.lang.String asid)
      throws javax.ejb.CreateException;

   public java.util.Collection findByUserId(java.lang.String userId)
      throws javax.ejb.FinderException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public org.emayor.servicehandling.interfaces.AccessSessionEntityLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
