/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for AccessSessionEntity.
 */
public interface AccessSessionEntityLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Getter for CMP Field asid
    */
   public java.lang.String getAsid(  ) ;

   /**
    * Setter for CMP Field asid
    */
   public void setAsid( java.lang.String value ) ;

   /**
    * Getter for CMP Field userId
    */
   public java.lang.String getUserId(  ) ;

   /**
    * Setter for CMP Field userId
    */
   public void setUserId( java.lang.String value ) ;

   /**
    * Getter for CMP Field startDate
    */
   public java.util.Date getStartDate(  ) ;

   /**
    * Setter for CMP Field startDate
    */
   public void setStartDate( java.util.Date value ) ;

}
