/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local home interface for AccessManager.
 */
public interface AccessManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AccessManagerLocal";
   public static final String JNDI_NAME="AccessManagerLocal";

   public org.emayor.servicehandling.interfaces.AccessManagerLocal create()
      throws javax.ejb.CreateException;

}
