/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local home interface for AdminManager.
 */
public interface AdminManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AdminManagerLocal";
   public static final String JNDI_NAME="AdminManagerLocal";

   public org.emayor.servicehandling.interfaces.AdminManagerLocal create(java.lang.String param)
      throws javax.ejb.CreateException;

}
