/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for AdminManager.
 */
public interface AdminManagerLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Business Method
    */
   public boolean isEnabled(  ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public boolean login( java.lang.String uid,java.lang.String pswd ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public void reloadServices(  ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public void reloadConfiguration(  ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.UserProfile[] listLoggedInUsers(  ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.UserProfile lookupUserProfile( java.lang.String uid ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.UserProfile[] listAllKnownUsers(  ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.AccessSessionInfo[] listAccessSessions(  ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.AccessSessionInfo lookupAccessSession( java.lang.String asid ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.ServiceSessionInfo[] listServiceSessions(  ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.ServiceSessionInfo lookupServiceSession( java.lang.String ssid ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.AdminServiceProfileData[] listDeployedServices(  ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.AdminServiceProfileData lookupServiceProfile( java.lang.String serviceId ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public void changeServiceStatus( java.lang.String serviceId,boolean active ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public void removeAccessSession( java.lang.String asid ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public void removeServiceSession( java.lang.String ssid ) throws org.emayor.servicehandling.kernel.AdminException;

   /**
    * Business Method
    */
   public void removeUserProfile( java.lang.String uid ) throws org.emayor.servicehandling.kernel.AdminException;

}
