/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for BPELCallbackDataEntity.
 */
public interface BPELCallbackDataEntityLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Getter for CMP Field ssid
    */
   public java.lang.String getSsid(  ) ;

   /**
    * Setter for CMP Field ssid
    */
   public void setSsid( java.lang.String value ) ;

   /**
    * Getter for CMP Field messageId
    */
   public java.lang.String getMessageId(  ) ;

   /**
    * Setter for CMP Field messageId
    */
   public void setMessageId( java.lang.String value ) ;

   /**
    * Getter for CMP Field address
    */
   public java.lang.String getAddress(  ) ;

   /**
    * Setter for CMP Field address
    */
   public void setAddress( java.lang.String value ) ;

   /**
    * Getter for CMP Field userId
    */
   public java.lang.String getUserId(  ) ;

   /**
    * Setter for CMP Field userId
    */
   public void setUserId( java.lang.String value ) ;

   /**
    * Getter for CMP Field portType
    */
   public java.lang.String getPortType(  ) ;

   /**
    * Setter for CMP Field portType
    */
   public void setPortType( java.lang.String value ) ;

   /**
    * Getter for CMP Field serviceName
    */
   public java.lang.String getServiceName(  ) ;

   /**
    * Setter for CMP Field serviceName
    */
   public void setServiceName( java.lang.String value ) ;

}
