/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Remote interface for BPELPolicyEnforcer.
 */
public interface BPELPolicyEnforcer
   extends javax.ejb.EJBObject
{
   /**
    * Business method
    */
   public boolean F_VerifyXMLSignature( java.lang.String xmlDocument )
      throws org.emayor.servicehandling.kernel.BPELPolicyEnforcerException, java.rmi.RemoteException;

   /**
    * Business method
    */
   public java.lang.String F_TimeStampXMLDocument( java.lang.String xmlDocumentDoc )
      throws org.emayor.servicehandling.kernel.BPELPolicyEnforcerException, java.rmi.RemoteException;

   /**
    * Business method
    */
   public boolean F_VerifyXMLTimeStampedDocument( java.lang.String xmlDocument )
      throws org.emayor.servicehandling.kernel.BPELPolicyEnforcerException, java.rmi.RemoteException;

   /**
    * Business method
    */
   public boolean F_AuthorizeServiceStep( java.lang.String userId,java.lang.String ssid,java.lang.String serviceStepId )
      throws org.emayor.servicehandling.kernel.BPELPolicyEnforcerException, java.rmi.RemoteException;

   /**
    * Business method
    */
   public boolean F_NewUserProfile( java.lang.String newUserProfile )
      throws java.rmi.RemoteException;

}
