/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Home interface for BPELPolicyEnforcer.
 */
public interface BPELPolicyEnforcerHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/BPELPolicyEnforcer";
   public static final String JNDI_NAME="ejb/emayor/sh/BPELPolicyEnforcer";

   public org.emayor.servicehandling.interfaces.BPELPolicyEnforcer create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
