/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local home interface for BPELCallbackDataEntity.
 */
public interface BPELCallbackDataEntityLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/BPELCallbackDataEntityLocal";
   public static final String JNDI_NAME="BPELCallbackDataEntityLocal";

   public org.emayor.servicehandling.interfaces.BPELCallbackDataEntityLocal create(java.lang.String ssid)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public java.util.Collection findByUserId(java.lang.String userId)
      throws javax.ejb.FinderException;

   public org.emayor.servicehandling.interfaces.BPELCallbackDataEntityLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
