/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Remote interface for E2MWrapper.
 */
public interface E2MWrapper
   extends javax.ejb.EJBObject
{
   /**
    * Business method
    */
   public java.lang.String serviceRequestPropagator( java.lang.String request,java.lang.String type )
      throws java.rmi.RemoteException;

}
