/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Home interface for E2MWrapper.
 */
public interface E2MWrapperHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/E2MWrapper";
   public static final String JNDI_NAME="ejb/emayor/sh/E2MWrapper";

   public org.emayor.servicehandling.interfaces.E2MWrapper create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
