/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local home interface for eMayorServiceFactory.
 */
public interface eMayorServiceFactoryLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/eMayorServiceFactoryLocal";
   public static final String JNDI_NAME="eMayorServiceFactoryLocal";

   public org.emayor.servicehandling.interfaces.eMayorServiceFactoryLocal create(java.lang.String param)
      throws javax.ejb.CreateException;

}
