/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for eMayorServiceFactory.
 */
public interface eMayorServiceFactoryLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Business method
    */
   public void setup(  ) throws org.emayor.servicehandling.kernel.eMayorServiceException;

   /**
    * Business method
    */
   public void cleanup(  ) throws org.emayor.servicehandling.kernel.eMayorServiceException;

   /**
    * Business method
    */
   public org.emayor.servicehandling.kernel.IeMayorService createService( java.lang.String serviceName,java.lang.String ssid ) throws org.emayor.servicehandling.kernel.eMayorServiceException;

}
