/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local home interface for ForwardManagerBPEL.
 */
public interface ForwardManagerBPELLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ForwardManagerBPELLocal";
   public static final String JNDI_NAME="ForwardManagerBPELLocal";

   public org.emayor.servicehandling.interfaces.ForwardManagerBPELLocal create()
      throws javax.ejb.CreateException;

}
