/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for ForwardManagerBPEL.
 */
public interface ForwardManagerBPELLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Business Method
    */
   public void forwardRequest( org.emayor.servicehandling.kernel.bpel.forward.data.ForwardMessageBPEL message ) ;

   /**
    * Business Method
    */
   public void forwardResponse( org.emayor.servicehandling.kernel.bpel.forward.data.ForwardMessageBPEL message ) ;

}
