/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for ForwardManager.
 */
public interface ForwardManagerLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Business Method
    */
   public void forwardRequest( org.emayor.servicehandling.kernel.forward.ForwardMessage forwardMessage ) ;

   /**
    * Business Method
    */
   public void forwardResponse( org.emayor.servicehandling.kernel.forward.ForwardMessage forwardMessage ) ;

}
