/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local home interface for ForwardManager.
 */
public interface ForwardManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ForwardManagerLocal";
   public static final String JNDI_NAME="ForwardManagerLocal";

   public org.emayor.servicehandling.interfaces.ForwardManagerLocal create()
      throws javax.ejb.CreateException;

}
