/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for Kernel.
 */
public interface KernelLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Business Method
    */
   public java.lang.String createAccessSession(  ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.interfaces.AccessSessionLocal getAccessSession( java.lang.String asid ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public boolean deleteAccessSession( java.lang.String asid ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.interfaces.ServiceSessionLocal createServiceSession( java.lang.String asid,java.lang.String serviceName,java.lang.String userId ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.interfaces.ServiceSessionLocal getServiceSession( java.lang.String ssid ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public boolean deleteServiceSession( java.lang.String asid,java.lang.String ssid ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.ServiceInfo[] listAvailableServices( org.eMayor.PolicyEnforcement.C_UserProfile userProfile ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.ServiceInfo[] listAllAvailableServices(  ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public java.lang.String getUserIdByASID( java.lang.String asid ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public java.lang.String getServiceClassNameByServiceName( java.lang.String serviceName ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.IUserProfile getUserProfile( java.lang.String userId ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.IServiceProfile getServiceProfile( java.lang.String ssid ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.IServiceProfile getServiceProfileByServiceId( java.lang.String serviceId ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public java.lang.String authenticateUser( java.lang.String asid,java.security.cert.X509Certificate[] certificates ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.interfaces.ServiceSessionLocal[] getUsersServiceSessions( java.lang.String userId ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public java.lang.String getAsidByUserID( java.lang.String userId ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public void addForwardBPELCallbackData( org.emayor.servicehandling.kernel.bpel.forward.data.ForwardBPELCallbackData data ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.bpel.forward.data.ForwardBPELCallbackData getForwardBPELCallbackData( java.lang.String ssid ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public void reloadDeployedServices(  ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.AccessSessionInfo[] listAccessSessions(  ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.ServiceSessionInfo[] listServiceSessions(  ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.ServiceSessionInfo[] listServiceSessions( java.lang.String uid ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.IUserProfile[] listUserProfiles(  ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.IUserProfile[] listLoggedInUsers(  ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public java.lang.String getNumberOfInstances( java.lang.String serviceId ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public java.util.HashMap getNumberOfInstancesMap(  ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public void resetNumberOfInstances(  ) throws org.emayor.servicehandling.kernel.KernelException;

   /**
    * Business Method
    */
   public void resetNumberOfInstances( java.lang.String serviceId ) throws org.emayor.servicehandling.kernel.KernelException;

}
