/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local home interface for PlatformConfigurationEntity.
 */
public interface PlatformConfigurationEntityLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PlatformConfigurationEntityLocal";
   public static final String JNDI_NAME="PlatformConfigurationEntityLocal";

   public org.emayor.servicehandling.interfaces.PlatformConfigurationEntityLocal create(java.lang.String configID)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public org.emayor.servicehandling.interfaces.PlatformConfigurationEntityLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
