/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for ServiceSession.
 */
public interface ServiceSessionLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Business Method
    */
   public java.lang.String getAccessSessionId(  ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public void setAccessSessionId( java.lang.String asid ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public java.lang.String getServiceId(  ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public void setServiceId( java.lang.String serviceId ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public void stopService( java.lang.String reason ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public java.lang.String getSessionId(  ) throws org.emayor.servicehandling.kernel.SessionException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.IeMayorService geteMayorService(  ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public void seteMayorService( org.emayor.servicehandling.kernel.IeMayorService emayorService ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public void startService( java.lang.String userId,boolean isForwarded,java.lang.String xmlDoc,java.lang.String docSig ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public void startServiceRequestCompleted( java.lang.String userId,boolean isForwarded,java.lang.String xmlDoc,java.lang.String docSig ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public void endService(  ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public java.util.Date getStartDate(  ) throws org.emayor.servicehandling.kernel.SessionException;

   /**
    * Business Method
    */
   public java.lang.String getCreatorId(  ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public void setCreatorId( java.lang.String creatorId ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

}
