/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local home interface for ServiceSession.
 */
public interface ServiceSessionLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ServiceSessionLocal";
   public static final String JNDI_NAME="ServiceSessionLocal";

   public org.emayor.servicehandling.interfaces.ServiceSessionLocal create(java.lang.String asid)
      throws javax.ejb.CreateException;

}
