/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for ServiceSession.
 */
public interface ServiceSessionLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Business Method
    */
   public java.lang.String getAccessSessionId(  ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public void setAccessSessionId( java.lang.String asid ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public java.lang.String getServiceName(  ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public java.lang.String getAccessURLString(  ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public void stopService(  ) throws org.emayor.servicehandling.kernel.ServiceSessionException;

   /**
    * Business Method
    */
   public java.lang.String getSessionId(  ) throws org.emayor.servicehandling.kernel.SessionException;

}
