/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local home interface for ServiceCallbackManager.
 */
public interface ServiceCallbackManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ServiceCallbackManagerLocal";
   public static final String JNDI_NAME="ServiceCallbackManagerLocal";

   public org.emayor.servicehandling.interfaces.ServiceCallbackManagerLocal create()
      throws javax.ejb.CreateException;

}
