/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for ServiceInfoEntity.
 */
public interface ServiceInfoEntityLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Getter for CMP Field serviceId
    */
   public java.lang.String getServiceId(  ) ;

   /**
    * Setter for CMP Field serviceId
    */
   public void setServiceId( java.lang.String value ) ;

   /**
    * Getter for CMP Field serviceVersion
    */
   public java.lang.String getServiceVersion(  ) ;

   /**
    * Setter for CMP Field serviceVersion
    */
   public void setServiceVersion( java.lang.String value ) ;

   /**
    * Getter for CMP Field serviceName
    */
   public java.lang.String getServiceName(  ) ;

   /**
    * Setter for CMP Field serviceName
    */
   public void setServiceName( java.lang.String value ) ;

   /**
    * Getter for CMP Field serviceClassName
    */
   public java.lang.String getServiceClassName(  ) ;

   /**
    * Setter for CMP Field serviceClassName
    */
   public void setServiceClassName( java.lang.String value ) ;

   /**
    * Getter for CMP Field serviceFactoryClassName
    */
   public java.lang.String getServiceFactoryClassName(  ) ;

   /**
    * Setter for CMP Field serviceFactoryClassName
    */
   public void setServiceFactoryClassName( java.lang.String value ) ;

   /**
    * Getter for CMP Field serviceDescription
    */
   public java.lang.String getServiceDescription(  ) ;

   /**
    * Setter for CMP Field serviceDescription
    */
   public void setServiceDescription( java.lang.String value ) ;

   /**
    * Getter for CMP Field serviceEndpoint
    */
   public java.lang.String getServiceEndpoint(  ) ;

   /**
    * Setter for CMP Field serviceEndpoint
    */
   public void setServiceEndpoint( java.lang.String value ) ;

   /**
    * Getter for CMP Field active
    */
   public java.lang.Boolean getActive(  ) ;

   /**
    * Setter for CMP Field active
    */
   public void setActive( java.lang.Boolean value ) ;

}
