/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for ServiceCallbackManager.
 */
public interface ServiceCallbackManagerLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Business Method
    */
   public java.lang.String onResult( org.emayor.servicehandling.kernel.ServiceCallbackData result ) ;

}
