/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for SimpleIdGenerator.
 */
public interface SimpleIdGeneratorLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Business Method
    */
   public java.lang.String generateId(  ) ;

}
