/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local home interface for SimpleIdGenerator.
 */
public interface SimpleIdGeneratorLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SimpleIdGeneratorLocal";
   public static final String JNDI_NAME="SimpleIdGeneratorLocal";

   public org.emayor.servicehandling.interfaces.SimpleIdGeneratorLocal create()
      throws javax.ejb.CreateException;

}
