/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for UserTaskManager.
 */
public interface UserTaskManagerLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.Tasks getMyTasks( java.lang.String accessSessionId ) throws org.emayor.servicehandling.kernel.ServiceException;

   /**
    * Business Method
    */
   public void completeTask( java.lang.String accessSessionId,org.emayor.servicehandling.kernel.Task task ) throws org.emayor.servicehandling.kernel.ServiceException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.Task lookupTask( java.lang.String taskId ) throws org.emayor.servicehandling.kernel.ServiceException;

   /**
    * Business Method
    */
   public org.emayor.servicehandling.kernel.Task lookupTaskByServiceSession( java.lang.String asid,java.lang.String ssid ) throws org.emayor.servicehandling.kernel.ServiceException;

}
