/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for UserProfileEntity.
 */
public interface UserProfileEntityLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Getter for CMP Field userId
    */
   public java.lang.String getUserId(  ) ;

   /**
    * Setter for CMP Field userId
    */
   public void setUserId( java.lang.String value ) ;

   /**
    * Getter for CMP Field c_UserProfile
    */
   public java.lang.String getC_UserProfile(  ) ;

   /**
    * Setter for CMP Field c_UserProfile
    */
   public void setC_UserProfile( java.lang.String value ) ;

}
