/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local home interface for UserProfileEntity.
 */
public interface UserProfileEntityLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UserProfileEntityLocal";
   public static final String JNDI_NAME="UserProfileEntityLocal";

   public org.emayor.servicehandling.interfaces.UserProfileEntityLocal create(java.lang.String userId)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public org.emayor.servicehandling.interfaces.UserProfileEntityLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
