/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local interface for UserTaskManager.
 */
public interface UserTaskManagerLocal
   extends javax.ejb.EJBLocalObject
{

}
