/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.interfaces;

/**
 * Local home interface for UserTaskManager.
 */
public interface UserTaskManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UserTaskManagerLocal";
   public static final String JNDI_NAME="UserTaskManagerLocal";

   public org.emayor.servicehandling.interfaces.UserTaskManagerLocal create()
      throws javax.ejb.CreateException;

}
