/*
 * Created on Mar 18, 2005
 * Exception generated by the Policy Enforcement
 * 
 */
package org.eMayor.PolicyEnforcement;

import java.io.Serializable;

/**
 * @author S. Tcaciuc
 * UoSiegen
 *
 * 
 */
public class E_PolicyEnforcementException extends Exception implements
		Serializable {
	 public E_PolicyEnforcementException(String s)
	   {
	      super(s);
	   }

}
