Sehr geehrte/r Herr/Frau ${REQ_TITLE} ${REQ_FORENAME} ${REQ_SURNAME},

Ihre Anfrage bzgl. einer Melderegisterbescheinigung für ${CP_FORENAME} ${CP_SURNAME}
(datiert vom ${REQ_DATE}) wurde bearbeitet. 
Sie können das Dokument jetzt auf der eMayor-Plattform herunterladen und auf Ihrem Rechner absichern. 
Danach können Sie das Formular ausdrucken.


Mit freundlichen Grüßen,

Landeseinwohneramt ${STATE}
