/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.notification.producer;

/**
 * Home interface for EmailNotificationProducer.
 */
public interface EmailNotificationProducerHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/EmailNotificationProducer";
   public static final String JNDI_NAME="ejb/EmailNotificationProducer";

   public org.emayor.notification.producer.EmailNotificationProducer create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
