/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.ContentRouting.interfaces;

/**
 * Home interface for ContentRouter.
 * @author Nikolaos Oikonomidis, University of Siegen
 */
public interface ContentRouterHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ContentRouter";
   public static final String JNDI_NAME="ejb/ContentRouter";

   public org.emayor.ContentRouting.interfaces.ContentRouter create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
