/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.ContentRouting.interfaces;

/**
 * Remote interface for ContentRouter.
 * @author Nikolaos Oikonomidis, University of Siegen
 */
public interface ContentRouter
   extends javax.ejb.EJBObject
{
   /**
    * The core business method of the content routing EJB. Provides the access point of a web-service as a URL.
    * @param municipalityName The name of the organization (municipality) to be queried.
    * @param serviceName The name of the requested service.
    * @return The URL of the access point for the requested service of the specific organization (municipality).
    * @throws org.emayor.ContentRouting.ejb.OrganisationNotFoundException when the requested organization could not be found.
    * @throws org.emayor.ContentRouting.ejb.ServiceNotFoundException when no service could be found for the given organization.
    * @throws org.emayor.ContentRouting.ejb.BindingTemplateNotFoundException when no binding template could be found for the given service.
    * @throws org.emayor.ContentRouting.ejb.AccessPointNotFoundException when no access point URL could be found for the given service.
    */
   public java.lang.String getAccessPoint( java.lang.String municipalityName,java.lang.String serviceName )
      throws org.emayor.ContentRouting.ejb.OrganisationNotFoundException, org.emayor.ContentRouting.ejb.ServiceNotFoundException, org.emayor.ContentRouting.ejb.BindingTemplateNotFoundException, org.emayor.ContentRouting.ejb.AccessPointNotFoundException, java.rmi.RemoteException;

}
