/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.ContentRouting.interfaces;

/**
 * Local home interface for ContentRouter.
 * @author Nikolaos Oikonomidis, University of Siegen
 */
public interface ContentRouterLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ContentRouterLocal";
   public static final String JNDI_NAME="ContentRouterLocal";

   public org.emayor.ContentRouting.interfaces.ContentRouterLocal create()
      throws javax.ejb.CreateException;

}
