/*
 * Generated by XDoclet - Do not edit!
 */
package org.eMayor.PolicyEnforcement.interfaces;

/**
 * Remote interface for PolicyEnforcement.
 */
public interface PolicyEnforcement
   extends javax.ejb.EJBObject
{
   /**
    * Business method
    */
   public org.eMayor.PolicyEnforcement.C_UserProfile F_getUserProfile( java.security.cert.X509Certificate[] x509_CertChain )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public boolean F_AuthenticateUser( org.eMayor.PolicyEnforcement.C_UserProfile UserProfile )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public boolean F_VerifyXMLSignature( java.lang.String xmlDocument )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public java.lang.String F_TimeStampXMLDocument( java.lang.String xmlDocumentDoc )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public boolean F_VerifyXMLTimeStampedDocument( java.lang.String xmlDocument )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public boolean F_AuthorizeService( org.eMayor.PolicyEnforcement.C_UserProfile UserProfile,org.eMayor.PolicyEnforcement.C_ServiceProfile ServiceProfile )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public boolean F_AuthorizeServiceStep( org.eMayor.PolicyEnforcement.C_UserProfile UserProfile,org.eMayor.PolicyEnforcement.C_ServiceProfile ServiceProfile,org.eMayor.PolicyEnforcement.C_ServiceStep ServiceStep )
      throws java.rmi.RemoteException;

}
