/*
 * Generated by XDoclet - Do not edit!
 */
package org.eMayor.PolicyEnforcement.interfaces;

/**
 * Local home interface for PolicyEnforcement.
 */
public interface PolicyEnforcementLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PolicyEnforcementLocal";
   public static final String JNDI_NAME="PolicyEnforcementLocal";

   public org.eMayor.PolicyEnforcement.interfaces.PolicyEnforcementLocal create()
      throws javax.ejb.CreateException;

}
