/*
 * Generated by XDoclet - Do not edit!
 */
package org.eMayor.ServiceHandling.PrintingUtility.interfaces;

/**
 * Home interface for Printer.
 */
public interface PrinterHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Printer";
   public static final String JNDI_NAME="ejb/Printer";

   public org.eMayor.ServiceHandling.PrintingUtility.interfaces.Printer create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
