/*
 * Generated by XDoclet - Do not edit!
 */
package org.eMayor.ServiceHandling.PrintingUtility.interfaces;

/**
 * Remote interface for Printer.
 */
public interface Printer
   extends javax.ejb.EJBObject
{
   /**
    * Business method
    */
   public void print( java.lang.String url,java.lang.String filetypeName )
      throws java.rmi.RemoteException;

}
