drop database if exists MUNICIPALITY_DB_NAME;

create database MUNICIPALITY_DB_NAME;

GRANT ALL PRIVILEGES ON MUNICIPALITY_DB_NAME.* TO jboss@localhost IDENTIFIED BY 'emayor';

use MUNICIPALITY_DB_NAME;

SOURCE create_config_table.sql

### default config ###
SET @CONFIG_ID = 'MUNICIPALITY_DB_NAME';
SET @MUNICIPALITY_ID = 'MUNICIPALITY_ID_NAME';
SET @MUNICIPALITY_NAME = 'Municipality of MUNICIPALITY_ID_NAME';

SET @BPEL_ENGINE_UT_SECURITY_DOMAIN_NAME = 'BPEL_DOMAIN';
SET @BPEL_ENGINE_UT_SECURITY_DOMAIN_PASSWORD = 'BPEL_PASSWORD';

SET @FORWARD_MANAGER_QUEUE_HOST = 'localhost:JBOSS_JNDI';
SET @FORWARD_MANAGER_TEST_LOCAL_MUNICIPALITY_NAME = 'MUNICIPALITY_ID_NAME';
SET @FORWARD_MANAGER_TEST_LOCAL_MUNICIPALITY_ADDRESS = 'https://localhost:8443/eMayorEJB/ForwardManager';
SET @FORWARD_MANAGER_TEST_REMOTE_MUNICIPALITY_NAME = 'Bozen';
SET @FORWARD_MANAGER_TEST_REMOTE_MUNICIPALITY_ADDRESS = 'https://localhost:18443/eMayorEJB/ForwardManager';

SET @EMAYOR_SERVICE_INVOKER_ENDPOINT = 'http://localhost:9700/orabpel/BPEL_DOMAIN/eMayorServiceStarter_v10/1.0';

SET @EMAYOR_CONTENTROUTING_LOCAL_INQUIRY = 'http://UDDI_HOST:28080/juddi/inquiry';
SET @EMAYOR_CONTENTROUTING_LOCAL_PUBLISH = 'http://UDDI_HOST:28080/juddi/publish';
SET @EMAYOR_CONTENTROUTING_REMOTE_INQUIRY = 'http://UDDI_HOST:28080/juddi/inquiry';
SET @EMAYOR_CONTENTROUTING_USERID = 'juddi';
SET @EMAYOR_CONTENTROUTING_PASSWORD = 'juddi';

SET @CONFIG_IS_ACTIVE = '1';

SET @EMAYOR_OPERATING_MODE = 'production';
SET @EMAYOR_OPERATING_MODE_CONTENT_ROUTING = 'production';
SET @EMAYOR_OPERATING_MODE_EMAIL = 'EMAIL_MODE';
SET @EMAYOR_OPERATING_MODE_FORWARD = 'production';

SET @EMAYOR_E2M_CONTEXT = 'E2MSERVER';

SET @EMAYOR_NOTIFICATION_EMAIL_REPLYTO = 'REPLYTO_ADDRESS';

SET @EMAYOR_PE_CRL_DISTRIBUTION_URL = 'http://localhost:JBOSS_1_HTTP/EMayor-operational.crl';

SET @EMAYOR_NOTIFICATION_EMAIL_SMTP_HOST = 'MAILHOST';
SET @EMAYOR_NOTIFICATION_EMAIL_SMTP_USER = 'EMAIL_USER';
SET @EMAYOR_NOTIFICATION_EMAIL_SMTP_PASS = 'EMAIL_PASS';
SET @EMAYOR_NOTIFICATION_EMAIL_SMTP_AUTH = 'EMAIL_AUTH';
SET @EMAYOR_NOTIFICATION_EMAIL_TESTADDRESS = 'EMAIL_TEST_ADDRESS';
SET @EMAYOR_PE_CHECK_SIGNATURE = 'SIGNATURE_CHECK';

SOURCE create_config_instance.sql;
SOURCE admin_services.sql; 
SOURCE RCS_v10.sql;

drop database if exists juddi;

create database juddi;

GRANT ALL PRIVILEGES ON juddi.* TO juddi@localhost IDENTIFIED BY 'juddi';

use juddi;

SOURCE juddi.sql