/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.notification.manager;

/**
 * Home interface for NotificationManager.
 * @see org.emayor.notification.interfaces.INotificationManager
 */
public interface NotificationManagerHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/NotificationManager";
   public static final String JNDI_NAME="ejb/NotificationManager";

   public org.emayor.notification.manager.NotificationManager create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
