/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.beans;

/**
 * CMP layer for BPELCallbackDataEntity.
 */
public abstract class BPELCallbackDataEntityCMP
   extends org.emayor.servicehandling.beans.BPELCallbackDataEntityEJB
   implements javax.ejb.EntityBean
{

   public void ejbLoad() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbLoad();
   }

   public void ejbStore() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
         super.ejbStore();
   }

   public void ejbActivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbPassivate();

   }

   public void setEntityContext(javax.ejb.EntityContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException, javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

   public abstract java.lang.String getSsid() ;

   public abstract void setSsid( java.lang.String ssid ) ;

   public abstract java.lang.String getMessageId() ;

   public abstract void setMessageId( java.lang.String messageId ) ;

   public abstract java.lang.String getAddress() ;

   public abstract void setAddress( java.lang.String address ) ;

   public abstract java.lang.String getUserId() ;

   public abstract void setUserId( java.lang.String userId ) ;

   public abstract java.lang.String getPortType() ;

   public abstract void setPortType( java.lang.String portType ) ;

   public abstract java.lang.String getServiceName() ;

   public abstract void setServiceName( java.lang.String serviceName ) ;

}
