/*
 * Generated by XDoclet - Do not edit!
 */
package org.emayor.servicehandling.beans;

/**
 * CMP layer for ServiceSessionBeanEntity.
 */
public abstract class ServiceSessionBeanEntityCMP
   extends org.emayor.servicehandling.beans.ServiceSessionBeanEntityEJB
   implements javax.ejb.EntityBean
{

   public void ejbLoad() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbLoad();
   }

   public void ejbStore() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
         super.ejbStore();
   }

   public void ejbActivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbPassivate();

   }

   public void setEntityContext(javax.ejb.EntityContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException, javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

   public abstract java.lang.String getSsid() ;

   public abstract void setSsid( java.lang.String ssid ) ;

   public abstract java.lang.String getAsid() ;

   public abstract void setAsid( java.lang.String asid ) ;

   public abstract java.lang.String getServiceId() ;

   public abstract void setServiceId( java.lang.String serviceId ) ;

   public abstract java.util.Date getStartDate() ;

   public abstract void setStartDate( java.util.Date startDate ) ;

}
