/*
 * Generated by XDoclet - Do not edit!
 */
package org.eMayor.repository.interfaces;

/**
 * Remote interface for RepositoryManager.
 */
public interface RepositoryManager
   extends javax.ejb.EJBObject
{

}
